@localhost=localhost:4004/sales-order
@id =923bdf29-d933-4e92-a8c0-75403df6f390
GET http://{{localhost}}/Customers
Content-Type: application/json
Authorization: Basic joaozinho:123456

###

POST  http://{{localhost}}/Customers
Content-Type: application/json
Authorization: Basic joaozinho:123456

{
    "id": "{{id}}",
    "firstName": "Gabriel",
    "lastName": "Pereira",
    "email":"Gabriel@gmail.com"
}

# entity customers{
#     key id: UUID;
#         firstName: String(20);
#         lastName: String(100);
#         email: String(255);
# }

###

DELETE  http://{{localhost}}/Customers({{id}})
Content-Type: application/json

###

PUT  http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "Gabriel"
}

###

PATCH  http://{{localhost}}/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "teste"
}

###

GET http://{{localhost}}/Customers?$filter=endswith(firstName,'-')
Content-Type: application/json
