@localhost=localhost:4004/sales-order
@id=dc241386-2686-49ab-b3c5-94cfc679678e
@customerid =923bdf29-d933-4e92-a8c0-75403df6f390

@productid=3683827d-c574-4541-bd43-b5597db6ec34


GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json
Authorization: Basic joaozinho:123456

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic joaozinho:123456


{
    "id": "{{id}}",
    "customer_id": "{{customerid}}",
    "totalAmount": 398,
    "items": [
        {
            "id":"5f533468-4d8b-45d2-95ec-f9e0c932da1f",
            "header_id": "{{id}}",
            "product_id": "{{productid}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id":"9cdc20c4-7b0f-4d18-b3eb-4c63abb0e941",
            "header_id": "{{id}}",
            "product_id": "{{productid}}",
            "quantity":5,
            "price": 1.99
        }
    ]
}

###

DELETE  http://{{localhost}}/SalesOrderHeaders({{id}})
Content-Type: application/json
Authorization: Basic joaozinho:123456


###

PUT  http://{{localhost}}/SalesOrderHeaders(id=a8313aa5-0f17-40d8-9f42-0eddcbbc6d3e)
Content-Type: application/json
Authorization: Basic joaozinho:123456


{
    "modifiedBy": "teste"
}

###

GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount ge 2000000

###

GET http://localhost:4004/odata/v4/main/SalesOrderHeaders?$filter=totalAmount le 200000

###

# funcionalidade de clonar pedidos

POST http://{{localhost}}/SalesOrderHeaders(4782978d-0c0d-408c-9313-66d83d57fcb5)/cloneSalesOrder
Content-Type: application/json
Authorization: Basic joaozinho:123456

{}

#http://localhost:4004/odata/v4/main/SalesOrderHeaders(4782978d-0c0d-408c-9313-66d83d57fcb5)


